// =====================================================================
//  src/lib/fallback.ts
//  Local Fallback System — Ali Jitam's Content Safety Net
//  When Gemini fails or times out, this module generates rich card data
//  from the local 4,000-word database. The user NEVER sees an error.
// =====================================================================

import type { FlashcardAIData } from "./gemini";

// ── Word Type → Arabic mapping ────────────────────────────────────────
const TYPE_ARABIC: Record<string, string> = {
  noun:        "اسم",
  verb:        "فعل",
  adjective:   "صفة",
  adverb:      "ظرف",
  preposition: "حرف جر",
  pronoun:     "ضمير",
  conjunction: "حرف عطف",
  phrase:      "عبارة",
  other:       "أخرى",
};

// ── Common Arabic translation fallbacks (top 200 words) ───────────────
const KNOWN_TRANSLATIONS: Record<string, string> = {
  abandon:    "يتخلى عن",
  ability:    "قدرة",
  absence:    "غياب",
  absorb:     "يمتص",
  abstract:   "مجرد",
  abundant:   "وفير",
  academic:   "أكاديمي",
  accomplish: "ينجز",
  accurate:   "دقيق",
  achieve:    "يحقق",
  accept:     "يقبل",
  access:     "وصول",
  account:    "حساب",
  act:        "يتصرف",
  action:     "فعل / عمل",
  active:     "نشط",
  actually:   "فعلياً",
  add:        "يضيف",
  address:    "عنوان",
  admit:      "يعترف",
  adult:      "بالغ",
  advance:    "يتقدم",
  advantage:  "ميزة",
  advice:     "نصيحة",
  affect:     "يؤثر",
  afraid:     "خائف",
  age:        "عمر",
  agree:      "يوافق",
  allow:      "يسمح",
  almost:     "تقريباً",
  alone:      "وحيد",
  already:    "بالفعل",
  also:       "أيضاً",
  always:     "دائماً",
  amount:     "كمية",
  ancient:    "قديم",
  animal:     "حيوان",
  announce:   "يعلن",
  answer:     "جواب",
  appear:     "يظهر",
  apply:      "يطبق",
  approach:   "يقترب",
  area:       "منطقة",
  argue:      "يجادل",
  arrange:    "يرتب",
  arrive:     "يصل",
  article:    "مقال",
  attempt:    "محاولة",
  attention:  "انتباه",
  authority:  "سلطة",
  available:  "متاح",
  avoid:      "يتجنب",
  aware:      "واعٍ",
  balance:    "توازن",
  base:       "قاعدة",
  basic:      "أساسي",
  beautiful:  "جميل",
  because:    "لأن",
  become:     "يصبح",
  before:     "قبل",
  begin:      "يبدأ",
  behind:     "خلف",
  believe:    "يعتقد",
  benefit:    "فائدة",
  best:       "أفضل",
  better:     "أحسن",
  between:    "بين",
  beyond:     "ما وراء",
  blood:      "دم",
  board:      "لوحة",
  body:       "جسم",
  book:       "كتاب",
  born:       "مولود",
  both:       "كلا",
  break:      "يكسر",
  bring:      "يحضر",
  brother:    "أخ",
  build:      "يبني",
  business:   "عمل تجاري",
  busy:       "مشغول",
  buy:        "يشتري",
  call:       "يتصل",
  capital:    "عاصمة",
  care:       "يهتم",
  carry:      "يحمل",
  case:       "حالة",
  catch:      "يمسك",
  cause:      "يسبب",
  center:     "مركز",
  certain:    "مؤكد",
  chance:     "فرصة",
  change:     "يتغير",
  character:  "شخصية",
  check:      "يتحقق",
  child:      "طفل",
  choice:     "اختيار",
  choose:     "يختار",
  city:       "مدينة",
  claim:      "يدّعي",
  class:      "صف",
  clear:      "واضح",
  close:      "يغلق",
  collect:    "يجمع",
  color:      "لون",
  come:       "يأتي",
  common:     "شائع",
  community:  "مجتمع",
  company:    "شركة",
  compare:    "يقارن",
  complete:   "يكمل",
  concern:    "قلق",
  condition:  "حالة",
  consider:   "يعتبر",
  contain:    "يحتوي",
  continue:   "يستمر",
  control:    "يتحكم",
  cost:       "تكلفة",
  country:    "بلد",
  couple:     "زوج",
  course:     "دورة",
  cover:      "يغطي",
  create:     "يخلق",
  culture:    "ثقافة",
  current:    "حالي",
  cut:        "يقطع",
  danger:     "خطر",
  dark:       "مظلم",
  data:       "بيانات",
  daughter:   "ابنة",
  deal:       "صفقة",
  death:      "موت",
  decide:     "يقرر",
  deep:       "عميق",
  degree:     "درجة",
  demand:     "طلب",
  describe:   "يصف",
  design:     "تصميم",
  detail:     "تفصيل",
  develop:    "يطور",
  different:  "مختلف",
  difficult:  "صعب",
  direction:  "اتجاه",
  discover:   "يكتشف",
  discuss:    "يناقش",
  disease:    "مرض",
  doctor:     "طبيب",
  door:       "باب",
  draw:       "يرسم",
  dream:      "حلم",
  drive:      "يقود",
  drop:       "يسقط",
  during:     "خلال",
  early:      "مبكر",
  earth:      "أرض",
  easy:       "سهل",
  economy:    "اقتصاد",
  education:  "تعليم",
  effect:     "تأثير",
  effort:     "جهد",
  either:     "أيضاً",
  employ:     "يوظف",
  encourage:  "يشجع",
  energy:     "طاقة",
  enjoy:      "يستمتع",
  enough:     "كافي",
  enter:      "يدخل",
  entire:     "كامل",
  environment: "بيئة",
  especially: "خاصةً",
  establish:  "يؤسس",
  even:       "حتى",
  event:      "حدث",
  ever:       "أبداً",
  every:      "كل",
  evidence:   "دليل",
  exactly:    "بالضبط",
  example:    "مثال",
  except:     "ماعدا",
  exist:      "يوجد",
  expect:     "يتوقع",
  experience: "تجربة",
  explain:    "يشرح",
  express:    "يعبر",
  face:       "وجه",
  fact:       "حقيقة",
  fail:       "يفشل",
  fall:       "يسقط",
  family:     "عائلة",
  far:        "بعيد",
  fast:       "سريع",
  father:     "أب",
  fear:       "خوف",
  feel:       "يشعر",
  field:      "حقل",
  fight:      "يقاتل",
  figure:     "شكل",
  fill:       "يملأ",
  final:      "نهائي",
  finally:    "أخيراً",
  find:       "يجد",
  fine:       "جيد",
  finger:     "إصبع",
  finish:     "ينهي",
  fire:       "نار",
  first:      "أول",
  fish:       "سمكة",
  floor:      "أرضية",
  fly:        "يطير",
  follow:     "يتبع",
  food:       "طعام",
  force:      "قوة",
  foreign:    "أجنبي",
  forget:     "ينسى",
  form:       "شكل",
  free:       "حر",
  friend:     "صديق",
  front:      "أمام",
  full:       "ممتلئ",
  future:     "مستقبل",
  garden:     "حديقة",
  general:    "عام",
  girl:       "فتاة",
  give:       "يعطي",
  glass:      "زجاج",
  goal:       "هدف",
  good:       "جيد",
  government: "حكومة",
  great:      "عظيم",
  green:      "أخضر",
  ground:     "أرض",
  group:      "مجموعة",
  grow:       "ينمو",
  growth:     "نمو",
  guide:      "دليل",
  hair:       "شعر",
  half:       "نصف",
  hand:       "يد",
  happen:     "يحدث",
  happy:      "سعيد",
  hard:       "صعب",
  head:       "رأس",
  health:     "صحة",
  hear:       "يسمع",
  heart:      "قلب",
  heavy:      "ثقيل",
  help:       "يساعد",
  high:       "عالي",
  history:    "تاريخ",
  hold:       "يمسك",
  home:       "منزل",
  hope:       "أمل",
  hot:        "حار",
  hour:       "ساعة",
  house:      "بيت",
  human:      "إنسان",
  idea:       "فكرة",
  image:      "صورة",
  imagine:    "يتخيل",
  impact:     "تأثير",
  important:  "مهم",
  improve:    "يحسن",
  include:    "يشمل",
  increase:   "يزيد",
  indeed:     "بالفعل",
  indicate:   "يشير",
  individual: "فرد",
  industry:   "صناعة",
  inform:     "يبلغ",
  inside:     "داخل",
  instead:    "بدلاً من",
  interest:   "اهتمام",
  international: "دولي",
  involve:    "يشمل",
  issue:      "قضية",
  item:       "عنصر",
  join:       "ينضم",
  just:       "فقط",
  keep:       "يبقي",
  key:        "مفتاح",
  kill:       "يقتل",
  kind:       "نوع",
  king:       "ملك",
  know:       "يعرف",
  knowledge:  "معرفة",
  land:       "أرض",
  language:   "لغة",
  large:      "كبير",
  last:       "أخير",
  late:       "متأخر",
  law:        "قانون",
  lead:       "يقود",
  learn:      "يتعلم",
  leave:      "يغادر",
  less:       "أقل",
  letter:     "رسالة",
  level:      "مستوى",
  life:       "حياة",
  light:      "ضوء",
  line:       "خط",
  list:       "قائمة",
  listen:     "يستمع",
  little:     "صغير",
  live:       "يعيش",
  long:       "طويل",
  look:       "ينظر",
  lose:       "يخسر",
  love:       "حب",
  low:        "منخفض",
};

/**
 * Generate fallback flashcard data from local database fields.
 * This is the Content Safety Net — it guarantees the user never sees an error.
 */
export function generateLocalFallback(
  word: string,
  type: string,
  definition: string,
  example: string
): FlashcardAIData {
  const arabicType = TYPE_ARABIC[type.toLowerCase()] ?? TYPE_ARABIC.other;
  const knownTranslation = KNOWN_TRANSLATIONS[word.toLowerCase()];

  // Use known translation if available, otherwise construct from definition
  const translation = knownTranslation ?? definition;

  // Generate 3 contextual examples from what we have
  const examples = [
    {
      english: example || `The word "${word}" is commonly used in English.`,
      arabic:  knownTranslation ? `مثال: ${knownTranslation}` : "مثال عملي على استخدام الكلمة",
    },
    {
      english: `I need to understand the ${type} "${word}" better.`,
      arabic:  `أحتاج أن أفهم ${arabicType} "${word}" بشكل أفضل`,
    },
    {
      english: `Can you use "${word}" in a sentence?`,
      arabic:  `هل يمكنك استخدام "${word}" في جملة؟`,
    },
  ];

  return {
    translation,
    posArabic: arabicType,
    examples,
  };
}

/**
 * Generate a local fallback for the AI Tutor panel.
 * Returns structured data matching the AiData interface.
 */
export function generateTutorFallback(
  word: string,
  type: string,
  definition: string,
  example: string
) {
  const arabicType = TYPE_ARABIC[type.toLowerCase()] ?? TYPE_ARABIC.other;
  const knownTranslation = KNOWN_TRANSLATIONS[word.toLowerCase()];

  return {
    meaning: knownTranslation
      ? `${knownTranslation} — ${definition}`
      : `${definition}`,
    story: `تعلمت كلمة "${word}" الجديدة اليوم. هذه الكلمة من نوع ${arabicType} وتستخدم كثيراً في اللغة الإنجليزية. مثال: ${example}`,
    mnemonic: `تذكر كلمة "${word}" من خلال ربطها بالمعنى: ${knownTranslation ?? definition}`,
    context_engine: [
      {
        style: "Academic",
        english: `The concept of "${word}" is fundamental in academic discourse.`,
        arabic: `مفهوم "${word}" أساسي في الخطاب الأكاديمي.`,
      },
      {
        style: "Casual",
        english: example || `I use the word "${word}" every day.`,
        arabic: `أستخدم كلمة "${word}" كل يوم.`,
      },
      {
        style: "Professional",
        english: `Understanding "${word}" is essential for professional communication.`,
        arabic: `فهم "${word}" ضروري للتواصل المهني.`,
      },
    ],
  };
}
